# Use Python 3.9 slim image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY ../../services/service2/requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the application code
COPY ../../services/service2/app.py .

# Expose port 5001
EXPOSE 5001

# Command to run the application
CMD ["python", "app.py"]